# Generated by Django 3.2.5 on 2021-08-07 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='author',
            field=models.CharField(default=datetime.datetime(2021, 8, 7, 11, 17, 44, 685798, tzinfo=utc), max_length=150, verbose_name='Author...'),
            preserve_default=False,
        ),
    ]
